name: base
channels:
- bioconda
- conda-forge
dependencies:
- pysam
- pandas
- numpy
- bioconductor-annotate=1.72.0
- bioconductor-annotationdbi=1.56.2
- bioconductor-apeglm=1.16.0
- bioconductor-biobase=2.54.0
- bioconductor-biocfilecache=2.2.0
- bioconductor-biocgenerics=0.40.0
- bioconductor-biocio=1.4.0
- bioconductor-biocparallel=1.28.3
- bioconductor-biomart=2.50.0
- bioconductor-biostrings=2.62.0
- bioconductor-bsgenome=1.62.0
- bioconductor-complexheatmap=2.10.0
- bioconductor-delayedarray=0.20.0
- bioconductor-deseq2=1.34.0
- bioconductor-dexseq=1.40.0
- bioconductor-drimseq=1.22.0
- bioconductor-edger=3.36.0
- bioconductor-genefilter=1.76.0
- bioconductor-geneplotter=1.72.0
- bioconductor-genomeinfodb=1.30.1
- bioconductor-genomeinfodbdata=1.2.7
- bioconductor-genomicalignments=1.30.0
- bioconductor-genomicfeatures=1.46.1
- bioconductor-genomicranges=1.46.1
- bioconductor-iranges=2.28.0
- bioconductor-keggrest=1.34.0
- bioconductor-limma=3.50.3
- bioconductor-matrixgenerics=1.6.0
- bioconductor-rhtslib=1.26.0
- bioconductor-rsamtools=2.10.0
- bioconductor-rtracklayer=1.54.0
- bioconductor-s4vectors=0.32.4
- bioconductor-summarizedexperiment=1.24.0
- bioconductor-tximport=1.22.0
- bioconductor-xvector=0.34.0
- bioconductor-zlibbioc=1.40.0
- r-abind=1.4_5
- r-anytime=0.3.9
- r-ashr=2.2_54
- r-askpass=1.1
- r-assertthat=0.2.1
- r-backports=1.4.1
- r-base=4.1.3
- r-base64enc=0.1_3
- r-bbmle=1.0.25
- r-bdsmatrix=1.3_6
- r-bh=1.81.0_1
- r-biocmanager=1.30.21
- r-bit=4.0.5
- r-bit64=4.0.5
- r-bitops=1.0_7
- r-blob=1.2.4
- r-boot=1.3_28.1
- r-brew=1.0_8
- r-brio=1.1.3
- r-broom=1.0.5
- r-bslib=0.5.0
- r-cachem=1.0.8
- r-callr=3.7.3
- r-car=3.1_2
- r-cardata=3.0_5
- r-caret=6.0_94
- r-cellranger=1.1.0
- r-circlize=0.4.15
- r-class=7.3_22
- r-cli=3.6.1
- r-clipr=0.8.0
- r-clock=0.7.0
- r-clue=0.3_64
- r-cluster=2.1.4
- r-coda=0.19_4
- r-codetools=0.2_19
- r-colorspace=2.1_0
- r-commonmark=1.9.0
- r-conflicted=1.2.0
- r-conquer=1.3.3
- r-corrplot=0.92
- r-cowplot=1.1.1
- r-cpp11=0.4.7
- r-crayon=1.5.2
- r-credentials=1.3.2
- r-crosstalk=1.2.0
- r-crul=1.4.0
- r-curl=4.3.3
- r-data.table=1.14.8
- r-dbi=1.1.3
- r-dbplyr=2.3.2
- r-desc=1.4.2
- r-devtools=2.4.5
- r-diagram=1.6.5
- r-diffobj=0.3.5
- r-digest=0.6.31
- r-doparallel=1.0.17
- r-downlit=0.4.2
- r-dplyr=1.1.2
- r-dt=0.28
- r-dtplyr=1.3.1
- r-e1071=1.7_13
- r-ellipsis=0.3.2
- r-emdbook=1.3.12
- r-essentials=4.1
- r-etrunct=0.1
- r-evaluate=0.21
- r-fansi=1.0.4
- r-farver=2.1.1
- r-fastmap=1.1.1
- r-filelock=1.0.2
- r-fontawesome=0.5.1
- r-forcats=1.0.0
- r-foreach=1.5.2
- r-foreign=0.8_84
- r-formatr=1.14
- r-fs=1.6.2
- r-futile.logger=1.4.3
- r-futile.options=1.0.1
- r-future=1.32.0
- r-future.apply=1.11.0
- r-gargle=1.4.0
- r-generics=0.1.3
- r-gert=1.9.2
- r-getopt=1.20.3
- r-getoptlong=1.0.5
- r-ggplot2=3.4.2
- r-ggpubr=0.6.0
- r-ggrepel=0.9.3
- r-ggsci=3.0.0
- r-ggsignif=0.6.4
- r-gh=1.4.0
- r-gistr=0.9.0
- r-gitcreds=0.1.2
- r-glmnet=4.1_7
- r-globaloptions=0.1.2
- r-globals=0.16.2
- r-glue=1.6.2
- r-googledrive=2.1.0
- r-googlesheets4=1.1.0
- r-gower=1.0.1
- r-gridextra=2.3
- r-gridtext=0.1.5
- r-gtable=0.3.3
- r-hardhat=1.3.0
- r-haven=2.5.2
- r-here=1.0.1
- r-hexbin=1.28.3
- r-highr=0.10
- r-hms=1.1.3
- r-htmltools=0.5.5
- r-htmlwidgets=1.6.2
- r-httpcode=0.3.0
- r-httpuv=1.6.11
- r-httr=1.4.6
- r-httr2=0.2.3
- r-hwriter=1.3.2.1
- r-ids=1.0.1
- r-ini=0.3.1
- r-invgamma=1.1
- r-ipred=0.9_14
- r-irdisplay=1.1
- r-irkernel=1.3.2
- r-irlba=2.3.5.1
- r-isoband=0.2.7
- r-iterators=1.0.14
- r-jpeg=0.1_10
- r-jquerylib=0.1.4
- r-jsonlite=1.8.5
- r-kernsmooth=2.23_21
- r-knitr=1.43
- r-labeling=0.4.2
- r-lambda.r=1.2.4
- r-later=1.3.1
- r-lattice=0.21_8
- r-lava=1.7.2.1
- r-lazyeval=0.2.2
- r-lifecycle=1.0.3
- r-listenv=0.9.0
- r-lme4=1.1_33
- r-lobstr=1.1.2
- r-locfit=1.5_9.7
- r-lubridate=1.9.2
- r-magrittr=2.0.3
- r-maps=3.4.1
- r-maptools=1.1_7
- r-markdown=1.7
- r-mass=7.3_58.3
- r-matrix=1.5_4.1
- r-matrixmodels=0.5_1
- r-matrixstats=1.0.0
- r-memoise=2.0.1
- r-memuse=4.2_3
- r-mgcv=1.8_42
- r-mime=0.12
- r-miniui=0.1.1.1
- r-minqa=1.2.5
- r-mixsqp=0.3_48
- r-modelmetrics=1.2.2.2
- r-modelr=0.1.11
- r-munsell=0.5.0
- r-mvtnorm=1.2_2
- r-nlme=3.1_162
- r-nloptr=2.0.3
- r-nnet=7.3_19
- r-numderiv=2016.8_1.1
- r-openssl=2.0.6
- r-openxlsx=4.2.5.2
- r-optparse=1.7.3
- r-parallelly=1.36.0
- r-pbdzmq=0.3_9
- r-pbkrtest=0.5.2
- r-pheatmap=1.0.12
- r-pillar=1.9.0
- r-pkgbuild=1.4.0
- r-pkgconfig=2.0.3
- r-pkgdown=2.0.7
- r-pkgload=1.3.2
- r-plogr=0.2.0
- r-plyr=1.8.8
- r-png=0.1_8
- r-polynom=1.4_1
- r-praise=1.0.0
- r-prettyunits=1.1.1
- r-proc=1.18.2
- r-processx=3.8.1
- r-prodlim=2023.03.31
- r-profvis=0.3.8
- r-progress=1.2.2
- r-progressr=0.13.0
- r-promises=1.2.0.1
- r-proxy=0.4_27
- r-pryr=0.1.6
- r-ps=1.7.5
- r-purrr=1.0.1
- r-quantmod=0.4.22
- r-quantreg=5.95
- r-r6=2.5.1
- r-ragg=1.2.5
- r-randomforest=4.7_1.1
- r-rappdirs=0.3.3
- r-rbokeh=0.5.2
- r-rcmdcheck=1.4.0
- r-rcolorbrewer=1.1_3
- r-rcpp=1.0.10
- r-rcpparmadillo=0.12.4.0.0
- r-rcppeigen=0.3.3.9.3
- r-rcppnumerical=0.5_0
- r-rcpptoml=0.2.2
- r-rcurl=1.98_1.12
- r-readr=2.1.4
- r-readxl=1.4.2
- r-recipes=1.0.6
- r-recommended=4.1
- r-rematch=1.0.1
- r-rematch2=2.1.2
- r-remotes=2.4.2
- r-repr=1.1.6
- r-reprex=2.0.2
- r-reshape2=1.4.4
- r-restfulr=0.0.15
- r-reticulate=1.30
- r-rio=0.5.29
- r-rjson=0.2.21
- r-rlang=1.1.1
- r-rmarkdown=2.22
- r-roxygen2=7.2.3
- r-rpart=4.1.19
- r-rprojroot=2.0.3
- r-rsqlite=2.3.1
- r-rstatix=0.7.2
- r-rstudioapi=0.14
- r-rversions=2.1.2
- r-rvest=1.0.3
- r-sass=0.4.6
- r-scales=1.2.1
- r-selectr=0.4_2
- r-sessioninfo=1.2.2
- r-shape=1.4.6
- r-shiny=1.7.4
- r-shinybs=0.61.1
- r-shinycssloaders=1.0.0
- r-shinydashboard=0.7.2
- r-shinyfiles=0.9.3
- r-shinyjs=2.1.0
- r-shinywidgets=0.7.6
- r-snow=0.4_4
- r-sourcetools=0.1.7_1
- r-sp=1.6_1
- r-sparsem=1.81
- r-spatial=7.3_16
- r-squarem=2021.1
- r-statmod=1.5.0
- r-stringi=1.7.12
- r-stringr=1.5.0
- r-survival=3.5_5
- r-sys=3.4.2
- r-systemfonts=1.0.4
- r-testthat=3.1.8
- r-textshaping=0.3.6
- r-tibble=3.2.1
- r-tidyr=1.3.0
- r-tidyselect=1.2.0
- r-tidyverse=2.0.0
- r-timechange=0.2.0
- r-timedate=4022.108
- r-tinytex=0.45
- r-triebeard=0.4.1
- r-truncnorm=1.0_9
- r-ttr=0.24.3
- r-tzdb=0.4.0
- r-urlchecker=1.0.1
- r-urltools=1.7.3
- r-usethis=2.2.0
- r-utf8=1.2.3
- r-uuid=1.1_0
- r-vctrs=0.6.2
- r-viridislite=0.4.1
- r-vroom=1.6.3
- r-waiter=0.2.5
- r-waldo=0.5.1
- r-whisker=0.4.1
- r-withr=2.5.0
- r-xfun=0.39
- r-xml=3.99_0.14
- r-xml2=1.3.4
- r-xopen=1.0.0
- r-xtable=1.8_4
- r-xts=0.13.1
- r-yaml=2.3.7
- r-zip=2.3.0
